version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264444537.dkr.ecr.us-east-1.amazonaws.com
      - echo "Retrieving the image repository URI..."E
      - echo "Image URI: $IMAGE_URI"
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t harshal-docker-repo .
      - echo "Tagging the image..."
      - docker tag harshal-docker-repo:latest 058264444537.dkr.ecr.us-east-1.amazonaws.com/meme-generator:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 058264444537.dkr.ecr.us-east-1.amazonaws.com/meme-generator:latest
      - echo "Build and push completed successfully!"
artifacts:
  files:
    - Dockerfile
    - '**/*'
    - '!node_modules/**/*'
